### ISSUE TITLE
Changes

### ISSUE THREAD

**Issue by paarals** [openpoke/decidim-module-newsletter_agenda#18]
**General configuration**
- [x] Apply a new font "Inter"
route: ~/decidim-canodrom/fonts
how to use: <link rel="preconnect" href="https://your-font-file-host/"> <link rel="stylesheet" href="https://your-font-file-host/inter.css"> downolad the font and test it 

- [x] Apply the new colors per default
Purple: #7636D2

**Introduction**
- [x] Introduction title with bold
- [x] Introduction text increased the size a little bit more [first see the font]

**General Transition**
- [ ] @microstudi make a proposal

**Body**
- [x] Body title increased the size a little bit more [first see the font]
- [x] Body event description limited to 250 characters
- [x] Size of events images has to be 1200 x 675
- [x] Body event title and image associated is clickable 

**Transition body to footer**
- [x] Add an arrow looking to the bottom after "But there is more"

**Footer**
- [x] Put some padding in the side of Bottom title

**Mobile**
- [x] Review responsive

**Comment by microstudi** [comment]
[fonts.zip](https://github.com/openpoke/decidim-module-newsletter_agenda/files/11419578/fonts.zip)

Fonts to use. Fonts are linked like the images, see an example:
https://gitlab.com/colectic/decidim-zehar/-/blob/main/app/packs/src/decidim/decidim_application.js
