### ISSUE TITLE
Agenda Newsletter without background circle and with lines

### ISSUE THREAD

**Issue by paarals** [openpoke/decidim-module-newsletter_agenda#24]
Option 2: A new template in the settings of the module, so the administrator of Decidim will only see the design they chose at the begging. 
- [x] Module configuration option
  ```ruby
  # All the themes available for choosing when creating a newsletter, in case they want more than one
  config_accessor :themes do
   [:canodrom, :capitalitat]
  end
  ```
- [x] Presentation of the header (remove background) 
- [x] New field in the header (Button with link, defaults to "Read more") 
- [x] Presentation of the footer 

Mobile version:
![Newsletter ECOD_mobile](https://github.com/openpoke/decidim-module-newsletter_agenda/assets/40388743/55ed7205-0b19-4be2-916c-4c12d519a741)

**Comment by microstudi** [comment]
Let's go for option 2 but configurable in the plugin's initializer settings:

```ruby
config_accessor :themes do
 [:canodrom, :capitalitat]
end
```
