### ISSUE TITLE
ID3. Nou newsletter template (admin cell)

### ISSUE THREAD

**Issue by microstudi** [openpoke/decidim-module-newsletter_agenda#5]
Automatic:
- [x] Logo on top from the organization
- [x] Social links from the organization

Automatic but customizable:
- [x] Background color from the organization
- [x] Default font color over the background
- [x] Footer image logo (Default from footer organization default)
- [x] Footer Address Text (default from module configuration option) 

From the form:
- [x] Subject
- [x] Section header:
  - [x] Title
  - [x] Hero image
  - [x] Intro text
  - [x] Call to action link text
  - [x] Call to action link url 
- [x] Section body
  - [x] Title (defaults to "Que hi ha durant la setmana"
  - [x] Subtitle (defaults to "del 7 al 15 de novembre"
  - [x] Box 1-4:
    - [x] Image
    - [x] Date & time (text)
    - [x] Title
    - [x] Description
    - [x] Call to action text
    - [x] Call to action url 
  - [x] Final text 
- [x] Section footer
  - [x] Title
  - [x] Box 1-3
    - [x] Image
    - [x] Date & time (text)
    - [x] Title
    - [x] Call to action text
    - [x] Call to action link

**Comment by paarals** [comment]
tested and closed
